{% set name = "phagepickr" %}
{% set version = "1.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/Alebraco/phagepickr
    git_tag: v1.0

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
    host:
        - python >=3.11
        - pip
    run:
        - python >=3.11
        - biopython
        - mafft
        - joblib
        - numpy
        - pandas
        - python-dateutil
        - pytz
        - scikit-learn
        - scipy
        - six
        - threadpoolctl
        - tzdata

about: 
    home: "https://github.com/Alebraco/phagepickr"
    summary: "A tool to design evolution-proof phage cocktails against pathogenic bacteria"
    author: Alessandro Oneto

extra:
    recipe-maintainers:
        - Alebraco